### ISSUE TITLE
free of target?

### ISSUE THREAD

**Issue by antoinewaugh** [mjj29/apama-string-codec#1]
Hi,

Does the data_t take ownership of the char* target? In reviewing your code I cannot determine who owns/deletes char* target.

https://github.com/mjj29/apama-string-codec/blob/master/StringCodec.cpp#L75

Thanks
Antoine

**Comment by mjj29** [comment]
Fair point, looks like there's a leak there. Fortunately this functionality will be in the product proper very soon (10.3.1 April release which will be released as a service pack on 10.3.0 as well as with the suite 10.4 release).

Are you trying to use this plugin? It depends on a number of files that are internal to Apama and we don't ship, this was just intended to drive the internal change (which doesn't have this bug fwiw, I checked) rather than be easily community accessible.

**Comment by antoinewaugh** [comment]
Actually I just came across your source and thought I’d point it out. Current we do use json + stringCodec avail in 10.3 and I was curious if this is the same source as the leak would then exist in our prod env.

More of a friendly observation . Thanks for clarifying

Antoine Waugh
Director
Relative Technologies
+61 404 157 246

________________________________

**Comment by mjj29** [comment]
It was copied from there, but the leak is in the multiple charset support which I was adding here. That's now been added to the product in 10.3.1 but without the leak. Thanks for the heads up though (:

**Comment by antoinewaugh** [comment]
Thanks for clarifying and your prompt response.

Say G’day to the team in Cambridge.
